from enum import Enum


class ArgentinaPlateType(Enum):
    VEHICULO_PRIVADO = 'Vehículo privado'
    VEHICULOS_DIPLOMATICO = 'Cuerpo diplomático'
    VEHICULOS_CONSULAR = 'Cuerpo consular'
    VEHICULOS_INTERNACIONALES = 'Organismos internacionales'
    VEHICULOS_MISSION = 'Misiones especiales'
    VEHICULOS_ADMINISTRATIVO = 'Personal administrativo'
    REMOLQUE = 'Remolque'
    VEHICULOS_RESTRICTED = 'Vehiculos restricted'
    TRAILER = 'Trailer'
    RNPA = 'RNPA'
    MOTOCICLETA_PARTICULAR = 'Motocicleta particular'
    MOTOCICLETA_RESTRICTED = 'Motocicleta restricted'



class ArgentinaPlateColor(Enum):
    TRANSPARENT_BG = (255, 255, 255, 0)
    SINE_WAVE = (240, 240, 240)
    VEHICULO_PRIVADO_BG = (255, 255, 255)
    VEHICULO_PRIVADO_TEXT = (0, 0, 0)
    VEHICULO_PRIVADO_RECT = (0, 51, 160)
    VEHICULOS_DIPLOMATICO_BG = (255, 255, 255)
    VEHICULOS_DIPLOMATICO_TEXT = (255, 255, 255)
    VEHICULOS_DIPLOMATICO_RECT = (0, 134, 178)
    VEHICULOS_DIPLOMATICO_SINE_WAVE = (0, 139, 185)
    VEHICULOS_CONSULAR_BG = (255, 255, 255)
    VEHICULOS_CONSULAR_TEXT = (255, 255, 255)
    VEHICULOS_CONSULAR_RECT = (0, 134, 178)
    VEHICULOS_CONSULAR_SINE_WAVE = (0, 139, 185)
    VEHICULOS_INTERNACIONALES_BG = (255, 255, 255)
    VEHICULOS_INTERNACIONALES_TEXT = (255, 255, 255)
    VEHICULOS_INTERNACIONALES_RECT = (0, 134, 178)
    VEHICULOS_INTERNACIONALES_SINE_WAVE = (0, 139, 185)
    VEHICULOS_MISSION_BG = (255, 255, 255)
    VEHICULOS_MISSION_TEXT = (255, 255, 255)
    VEHICULOS_MISSION_RECT = (0, 134, 178)
    VEHICULOS_MISSION_SINE_WAVE = (0, 139, 185)
    VEHICULOS_ADMINISTRATIVO_BG = (255, 255, 255)
    VEHICULOS_ADMINISTRATIVO_TEXT = (255, 255, 255)
    VEHICULOS_ADMINISTRATIVO_RECT = (0, 134, 178)
    VEHICULOS_ADMINISTRATIVO_SINE_WAVE = (0, 139, 185)
    REMOLQUE_BG = (255, 255, 255)
    REMOLQUE_TEXT = (255, 255, 255)
    REMOLQUE_ARGENTINA = (0, 134, 178)
    REMOLQUE_RECT = (0, 0, 0)
    REMOLQUE_SINE_WAVE = (32, 32, 32)
    VEHICULOS_RESTRICTED_BG = (255, 255, 255)
    VEHICULOS_RESTRICTED_TEXT = (0, 108, 57)
    VEHICULOS_RESTRICTED_ARGENTINA = (255, 255, 255)
    VEHICULOS_RESTRICTED_RECT = (0, 51, 160)
    VEHICULOS_RESTRICTED_SINE_WAVE = (32, 32, 32)
    TRAILER_BG = (255, 255, 255)
    TRAILER_TEXT = (0, 0, 0)
    TRAILER_ARGENTINA = (255, 255, 255)
    TRAILER_RECT = (119, 32, 30)
    TRAILER_SINE_WAVE = (32, 32, 32)
    RNPA_BG = (0, 0, 0)
    RNPA_TEXT = (255, 255, 255)
    RNPA_SINE_WAVE = (32, 32, 32)


def plate_argentina():
    return {
        "country": "Argentina",
        "rfy": "2014",  # registration format year
        "font": "EuroPlate.ttf",
        "plates": [
            {
                "name": ArgentinaPlateType.VEHICULOS_DIPLOMATICO.value,
                "width": 342,
                "height": 150,
                "color_bg": ArgentinaPlateColor.VEHICULOS_DIPLOMATICO_BG.value,
                "color_text": ArgentinaPlateColor.VEHICULOS_DIPLOMATICO_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_DIPLOMATICO_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 342,
                        "height": 150,
                        "coord": 0
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_DIPLOMATICO_RECT.value,
                        "border_color": ArgentinaPlateColor.VEHICULOS_DIPLOMATICO_RECT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 6,
                        "start_y": 35,
                        "width": 328,
                        "height": 88,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_DIPLOMATICO_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 6,
                        "start_y": 85,
                        "end_x": 333,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_DIPLOMATICO_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 6,
                        "start_y": 86,
                        "end_x": 333,
                        "end_y": 86,
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_DIPLOMATICO_BG.value,
                        "start_x": 17,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'D123xxA'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['D']},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             ]
                        ]
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/mreciyc.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 24,
                        "start_y": 10,
                        "width": 12,
                        "height": 18,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ARGENTINA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_DIPLOMATICO_RECT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 108,
                        "start_y": 10,
                        "width": 132,
                        "height": 18,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "NotoSerif-Medium.ttf"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"PROPIEDAD MRECIyC",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_DIPLOMATICO_RECT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 110,
                        "start_y": 128,
                        "width": 122,
                        "height": 8,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "Arimo-SemiBold.ttf"
                    },
                ]
            },
            {
                "name": ArgentinaPlateType.VEHICULOS_CONSULAR.value,
                "width": 342,
                "height": 150,
                "color_bg": ArgentinaPlateColor.VEHICULOS_CONSULAR_BG.value,
                "color_text": ArgentinaPlateColor.VEHICULOS_CONSULAR_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_CONSULAR_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 342,
                        "height": 150,
                        "coord": 0
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_CONSULAR_RECT.value,
                        "border_color": ArgentinaPlateColor.VEHICULOS_CONSULAR_RECT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 6,
                        "start_y": 35,
                        "width": 328,
                        "height": 88,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_CONSULAR_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 6,
                        "start_y": 85,
                        "end_x": 333,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_CONSULAR_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 6,
                        "start_y": 86,
                        "end_x": 333,
                        "end_y": 86,
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_CONSULAR_BG.value,
                        "start_x": 17,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'D123xxA'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['C']},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             ]
                        ]
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/mreciyc.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 24,
                        "start_y": 10,
                        "width": 12,
                        "height": 18,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ARGENTINA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_CONSULAR_RECT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 108,
                        "start_y": 10,
                        "width": 132,
                        "height": 18,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "NotoSerif-Medium.ttf"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"PROPIEDAD MRECIyC",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_CONSULAR_RECT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 110,
                        "start_y": 128,
                        "width": 122,
                        "height": 8,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "Arimo-SemiBold.ttf"
                    },
                ]
            },
            {
                "name": ArgentinaPlateType.VEHICULOS_INTERNACIONALES.value,
                "width": 342,
                "height": 150,
                "color_bg": ArgentinaPlateColor.VEHICULOS_INTERNACIONALES_BG.value,
                "color_text": ArgentinaPlateColor.VEHICULOS_INTERNACIONALES_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_INTERNACIONALES_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 342,
                        "height": 150,
                        "coord": 0
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_INTERNACIONALES_RECT.value,
                        "border_color": ArgentinaPlateColor.VEHICULOS_INTERNACIONALES_RECT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 6,
                        "start_y": 35,
                        "width": 328,
                        "height": 88,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_INTERNACIONALES_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 6,
                        "start_y": 85,
                        "end_x": 333,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_INTERNACIONALES_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 6,
                        "start_y": 86,
                        "end_x": 333,
                        "end_y": 86,
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_INTERNACIONALES_BG.value,
                        "start_x": 17,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'D123xxA'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['I']},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             ]
                        ]
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/mreciyc.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 24,
                        "start_y": 10,
                        "width": 12,
                        "height": 18,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ARGENTINA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_INTERNACIONALES_RECT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 108,
                        "start_y": 10,
                        "width": 132,
                        "height": 18,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "NotoSerif-Medium.ttf"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"PROPIEDAD MRECIyC",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_INTERNACIONALES_RECT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 110,
                        "start_y": 128,
                        "width": 122,
                        "height": 8,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "Arimo-SemiBold.ttf"
                    },
                ]
            },
            {
                "name": ArgentinaPlateType.VEHICULOS_MISSION.value,
                "width": 342,
                "height": 150,
                "color_bg": ArgentinaPlateColor.VEHICULOS_MISSION_BG.value,
                "color_text": ArgentinaPlateColor.VEHICULOS_MISSION_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_MISSION_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 342,
                        "height": 150,
                        "coord": 0
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_MISSION_RECT.value,
                        "border_color": ArgentinaPlateColor.VEHICULOS_MISSION_RECT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 6,
                        "start_y": 35,
                        "width": 328,
                        "height": 88,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_MISSION_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 6,
                        "start_y": 85,
                        "end_x": 333,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_MISSION_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 6,
                        "start_y": 86,
                        "end_x": 333,
                        "end_y": 86,
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_MISSION_BG.value,
                        "start_x": 17,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'D123xxA'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['M']},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             ]
                        ]
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/mreciyc.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 24,
                        "start_y": 10,
                        "width": 12,
                        "height": 18,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ARGENTINA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_MISSION_RECT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 108,
                        "start_y": 10,
                        "width": 132,
                        "height": 18,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "NotoSerif-Medium.ttf"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"PROPIEDAD MRECIyC",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_MISSION_RECT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 110,
                        "start_y": 128,
                        "width": 122,
                        "height": 8,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "Arimo-SemiBold.ttf"
                    },
                ]
            },
            {
                "name": ArgentinaPlateType.VEHICULOS_ADMINISTRATIVO.value,
                "width": 342,
                "height": 150,
                "color_bg": ArgentinaPlateColor.VEHICULOS_ADMINISTRATIVO_BG.value,
                "color_text": ArgentinaPlateColor.VEHICULOS_ADMINISTRATIVO_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_ADMINISTRATIVO_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 342,
                        "height": 150,
                        "coord": 0
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_ADMINISTRATIVO_RECT.value,
                        "border_color": ArgentinaPlateColor.VEHICULOS_ADMINISTRATIVO_RECT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 6,
                        "start_y": 35,
                        "width": 328,
                        "height": 88,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_ADMINISTRATIVO_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 6,
                        "start_y": 85,
                        "end_x": 333,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_ADMINISTRATIVO_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 6,
                        "start_y": 86,
                        "end_x": 333,
                        "end_y": 86,
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_ADMINISTRATIVO_BG.value,
                        "start_x": 17,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'D123xxA'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74},
                                                 {'ox': 9, 'oy': 0, 'w': 36, 'h': 74}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A']},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             ]
                        ]
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/mreciyc.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 24,
                        "start_y": 10,
                        "width": 12,
                        "height": 18,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ARGENTINA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_ADMINISTRATIVO_RECT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 108,
                        "start_y": 10,
                        "width": 132,
                        "height": 18,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "NotoSerif-Medium.ttf"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"PROPIEDAD MRECIyC",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_ADMINISTRATIVO_RECT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 110,
                        "start_y": 128,
                        "width": 122,
                        "height": 8,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "Arimo-SemiBold.ttf"
                    },
                ]
            },
            {
                "name": ArgentinaPlateType.REMOLQUE.value,
                "width": 342,
                "height": 150,
                "color_bg": ArgentinaPlateColor.REMOLQUE_BG.value,
                "color_text": ArgentinaPlateColor.REMOLQUE_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.REMOLQUE_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 342,
                        "height": 150,
                        "coord": 0
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": ArgentinaPlateColor.REMOLQUE_RECT.value,
                        "border_color": ArgentinaPlateColor.REMOLQUE_RECT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 6,
                        "start_y": 35,
                        "width": 328,
                        "height": 88,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.REMOLQUE_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 6,
                        "start_y": 85,
                        "end_x": 333,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.REMOLQUE_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 6,
                        "start_y": 86,
                        "end_x": 333,
                        "end_y": 86,
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.REMOLQUE_BG.value,
                        "start_x": 12,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'D123xxA'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 28, 'h': 74},
                                                 {'ox': 4, 'oy': 0, 'w': 28, 'h': 74},
                                                 {'ox': 4, 'oy': 0, 'w': 28, 'h': 74},
                                                 {'ox': 20, 'oy': 0, 'w': 28, 'h': 74},
                                                 {'ox': 4, 'oy': 0, 'w': 28, 'h': 74},
                                                 {'ox': 4, 'oy': 0, 'w': 28, 'h': 74},
                                                 {'ox': 20, 'oy': 0, 'w': 28, 'h': 74},
                                                 {'ox': 4, 'oy': 0, 'w': 28, 'h': 74},
                                                 {'ox': 4, 'oy': 0, 'w': 28, 'h': 74}]},
                             {'type': 5, 'sl': {}},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             ]
                        ]
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/mreciyc.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 24,
                        "start_y": 10,
                        "width": 12,
                        "height": 18,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ARGENTINA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.REMOLQUE_ARGENTINA.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 108,
                        "start_y": 10,
                        "width": 132,
                        "height": 18,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "NotoSerif-Medium.ttf"
                    },
                ]
            },
            {
                "name": ArgentinaPlateType.VEHICULO_PRIVADO.value,
                "width": 400,
                "height": 130,
                "color_bg": ArgentinaPlateColor.VEHICULO_PRIVADO_BG.value,
                "color_text": ArgentinaPlateColor.VEHICULO_PRIVADO_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.VEHICULO_PRIVADO_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 400,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 400,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.VEHICULO_PRIVADO_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 397,
                        "height": 33,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULO_PRIVADO_TEXT.value,
                        "start_x": 24,
                        "start_y": 46,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'AB123CD'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 10, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 30, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 12, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 12, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 30, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 10, 'oy': 0, 'w': 35, 'h': 64}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": ArgentinaPlateColor.VEHICULO_PRIVADO_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 400,
                        "height": 130,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/Flag_of_Mercosur.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 18,
                        "start_y": 8,
                        "width": 34,
                        "height": 26,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/Argentina_flag.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 353,
                        "start_y": 12,
                        "width": 28,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"REPUBLICA ARGENTINA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULO_PRIVADO_BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 108,
                        "start_y": 22,
                        "width": 176,
                        "height": 12,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": ArgentinaPlateType.VEHICULOS_RESTRICTED.value,
                "width": 400,
                "height": 130,
                "color_bg": ArgentinaPlateColor.VEHICULOS_RESTRICTED_BG.value,
                "color_text": ArgentinaPlateColor.VEHICULOS_RESTRICTED_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_RESTRICTED_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 400,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 400,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.VEHICULOS_RESTRICTED_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 397,
                        "height": 33,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_RESTRICTED_TEXT.value,
                        "start_x": 24,
                        "start_y": 46,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'AB123CD'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 10, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 30, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 12, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 12, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 30, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 10, 'oy': 0, 'w': 35, 'h': 64}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": ArgentinaPlateColor.VEHICULOS_RESTRICTED_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 400,
                        "height": 130,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/Flag_of_Mercosur.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 18,
                        "start_y": 8,
                        "width": 34,
                        "height": 26,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/Argentina_flag.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 353,
                        "start_y": 12,
                        "width": 28,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"REPUBLICA ARGENTINA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_RESTRICTED_BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 146,
                        "start_y": 11,
                        "width": 108,
                        "height": 8,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"VEHÍCULOS CON CIRCULACIÓN RESTRINGIDA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_RESTRICTED_BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 78,
                        "start_y": 24,
                        "width": 240,
                        "height": 10,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": ArgentinaPlateType.TRAILER.value,
                "width": 400,
                "height": 130,
                "color_bg": ArgentinaPlateColor.TRAILER_BG.value,
                "color_text": ArgentinaPlateColor.TRAILER_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.TRAILER_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 400,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 400,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.TRAILER_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 397,
                        "height": 33,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.TRAILER_TEXT.value,
                        "start_x": 24,
                        "start_y": 46,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'AB123CD'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 10, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 30, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 12, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 12, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 30, 'oy': 0, 'w': 35, 'h': 64},
                                                 {'ox': 10, 'oy': 0, 'w': 35, 'h': 64}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": ArgentinaPlateColor.TRAILER_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 400,
                        "height": 130,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/Argentina_flag.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 353,
                        "start_y": 12,
                        "width": 28,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"TRAILER",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.TRAILER_BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 160,
                        "start_y": 16,
                        "width": 80,
                        "height": 15,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"DNRPA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.TRAILER_BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 20,
                        "start_y": 18,
                        "width": 46,
                        "height": 10,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": ArgentinaPlateType.RNPA.value,
                "width": 342,
                "height": 150,
                "color_bg": ArgentinaPlateColor.RNPA_BG.value,
                "color_text": ArgentinaPlateColor.RNPA_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.RNPA_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 342,
                        "height": 150,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.RNPA_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 6,
                        "start_y": 85,
                        "end_x": 333,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.RNPA_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 6,
                        "start_y": 86,
                        "end_x": 333,
                        "end_y": 86,
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.RNPA_TEXT.value,
                        "start_x": 26,
                        "start_y": 50,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'ABC12'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 36, 'h': 54},
                                                 {'ox': 22, 'oy': 0, 'w': 36, 'h': 54},
                                                 {'ox': 22, 'oy': 0, 'w': 36, 'h': 54},
                                                 {'ox': 47, 'oy': 0, 'w': 36, 'h': 54},
                                                 {'ox': 22, 'oy': 0, 'w': 36, 'h': 54}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 99, 'zfil': 2},
                             ]
                        ]
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"REPUBLICA ARGENTINA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.RNPA_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 24,
                        "start_y": 110,
                        "width": 288,
                        "height": 18,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"R   N   P   A",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.RNPA_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 102,
                        "start_y": 20,
                        "width": 140,
                        "height": 20,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": ArgentinaPlateType.MOTOCICLETA_PARTICULAR.value,
                "width": 200,
                "height": 170,
                "color_bg": ArgentinaPlateColor.VEHICULO_PRIVADO_BG.value,
                "color_text": ArgentinaPlateColor.VEHICULO_PRIVADO_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.VEHICULO_PRIVADO_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 200,
                        "height": 170,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 200,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 200,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.VEHICULO_PRIVADO_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 192,
                        "height": 29,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULO_PRIVADO_TEXT.value,
                        "start_x": 44,
                        "start_y": 38,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'AB123CD'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 28, 'h': 54},
                                                 {'ox': 10, 'oy': 0, 'w': 28, 'h': 54},
                                                 {'ox': 10, 'oy': 0, 'w': 28, 'h': 54},
                                                 {'ox': 25, 'oy': 100, 'w': 28, 'h': 54, 'r': False},
                                                 {'ox': 10, 'oy': 0, 'w': 28, 'h': 54},
                                                 {'ox': 10, 'oy': 0, 'w': 28, 'h': 54},
                                                 {'ox': 10, 'oy': 0, 'w': 28, 'h': 54}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": ArgentinaPlateColor.VEHICULO_PRIVADO_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 200,
                        "height": 170,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/Flag_of_Mercosur.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 9,
                        "start_y": 8,
                        "width": 28,
                        "height": 22,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/Argentina_flag.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 162,
                        "start_y": 8,
                        "width": 24,
                        "height": 16,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"REPUBLICA ARGENTINA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULO_PRIVADO_BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 47,
                        "start_y": 20,
                        "width": 102,
                        "height": 6,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": ArgentinaPlateType.MOTOCICLETA_RESTRICTED.value,
                "width": 200,
                "height": 170,
                "color_bg": ArgentinaPlateColor.VEHICULO_PRIVADO_BG.value,
                "color_text": ArgentinaPlateColor.VEHICULO_PRIVADO_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.VEHICULO_PRIVADO_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 200,
                        "height": 170,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 200,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": ArgentinaPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 200,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": ArgentinaPlateColor.VEHICULO_PRIVADO_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 192,
                        "height": 29,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULOS_RESTRICTED_TEXT.value,
                        "start_x": 44,
                        "start_y": 38,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'AB123CD'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 28, 'h': 54},
                                                 {'ox': 10, 'oy': 0, 'w': 28, 'h': 54},
                                                 {'ox': 10, 'oy': 0, 'w': 28, 'h': 54},
                                                 {'ox': 25, 'oy': 100, 'w': 28, 'h': 54, 'r': False},
                                                 {'ox': 10, 'oy': 0, 'w': 28, 'h': 54},
                                                 {'ox': 10, 'oy': 0, 'w': 28, 'h': 54},
                                                 {'ox': 10, 'oy': 0, 'w': 28, 'h': 54}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": ArgentinaPlateColor.VEHICULOS_RESTRICTED_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 200,
                        "height": 170,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/Flag_of_Mercosur.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 9,
                        "start_y": 8,
                        "width": 28,
                        "height": 22,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Argentina/Argentina_flag.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 162,
                        "start_y": 8,
                        "width": 24,
                        "height": 16,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"REPUBLICA ARGENTINA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULO_PRIVADO_BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 74,
                        "start_y": 16,
                        "width": 52,
                        "height": 4,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"VEHÍCULOS CON CIRCULACIÓN RESTRINGIDA",
                        "color_bg": ArgentinaPlateColor.TRANSPARENT_BG.value,
                        "color_text": ArgentinaPlateColor.VEHICULO_PRIVADO_BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 43,
                        "start_y": 23,
                        "width": 114,
                        "height": 6,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
        ]
    }
