from enum import Enum


class EcuadorPlateType(Enum):
    VEHICULOS_COMERCIALES = 'Vehículos comerciales'
    VEHICULOS_GUBERNAMENTALES = 'Vehículos gubernamentales'
    VEHICULOS_OFICIAL = 'Vehículos de uso oficial'
    VEHICULOS_REGIONES = 'Vehículos de los gobiernos autónomos descentralizados'
    VEHICULO_PRIVADO = 'Vehículo privado'
    VEHICULO_PRIVADO_DUPLICATA = 'Vehículo privado duplicata'
    VEHICULOS_DIPLOMATICO = 'Vehículos de servicio diplomático'
    VEHICULOS_TEMPORAL = 'Matrícula temporal'
    VEHICULOS_INTERNACION_TEMPORAL = 'Vehículos de internación temporal'
    VEHICULO_POLICIA = 'Policía Nacional del Ecuador'


class EcuadorPlateColor(Enum):
    TRANSPARENT_BG = (255, 255, 255, 0)
    SINE_WAVE = (240, 240, 240)
    VEHICULOS_DIPLOMATICO_BG = (255, 255, 255)
    VEHICULOS_DIPLOMATICO_TEXT = (0, 0, 0)
    VEHICULOS_DIPLOMATICO_RECT = (107, 174, 238)
    VEHICULO_PRIVADO_BG = (255, 255, 255)
    VEHICULO_PRIVADO_TEXT = (0, 0, 0)
    VEHICULO_PRIVADO_RECT = (255, 255, 255)
    VEHICULO_PRIVADO_DUPLICATA_BG = (255, 255, 255)
    VEHICULO_PRIVADO_DUPLICATA_TEXT = (0, 0, 0)
    VEHICULO_PRIVADO_DUPLICATA_RECT = (255, 255, 255)
    VEHICULOS_OFICIAL_BG = (255, 255, 255)
    VEHICULOS_OFICIAL_TEXT = (0, 0, 0)
    VEHICULOS_OFICIAL_RECT = (253, 254, 55)
    VEHICULOS_GUBERNAMENTALES_BG = (255, 255, 255)
    VEHICULOS_GUBERNAMENTALES_TEXT = (0, 0, 0)
    VEHICULOS_GUBERNAMENTALES_RECT = (253, 254, 55)
    VEHICULOS_REGIONES_BG = (255, 255, 255)
    VEHICULOS_REGIONES_TEXT = (0, 0, 0)
    VEHICULOS_REGIONES_RECT = (0, 188, 0)
    VEHICULOS_COMERCIALES_BG = (255, 255, 255)
    VEHICULOS_COMERCIALES_TEXT = (0, 0, 0)
    VEHICULOS_COMERCIALES_RECT = (235, 111, 0)
    VEHICULO_POLICIA_BG = (255, 255, 255)
    VEHICULO_POLICIA_TEXT = (0, 0, 0)
    VEHICULO_POLICIA_RECT = (255, 255, 255)
    VEHICULOS_TEMPORAL_BG = (0, 0, 0)
    VEHICULOS_TEMPORAL_TEXT = (255, 255, 255)
    VEHICULOS_TEMPORAL_RECT = (0, 0, 0)
    VEHICULOS_TEMPORAL_SINE_WAVE = (32, 32, 32)
    VEHICULOS_INTERNACION_TEMPORAL_BG = (255, 255, 255)
    VEHICULOS_INTERNACION_TEMPORAL_TEXT = (0, 0, 0)
    VEHICULOS_INTERNACION_TEMPORAL_RECT = (255, 0, 0)


def plate_ecuador():
    return {
        "country": "Ecuador",
        "rfy": "2012",  # registration format year
        "font": "EuroPlate.ttf",
        "plates": [
            {
                "name": EcuadorPlateType.VEHICULOS_DIPLOMATICO.value,
                "width": 404,
                "height": 154,
                "color_bg": EcuadorPlateColor.VEHICULOS_DIPLOMATICO_BG.value,
                "color_text": EcuadorPlateColor.VEHICULOS_DIPLOMATICO_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_DIPLOMATICO_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 400,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 400,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_DIPLOMATICO_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 397,
                        "height": 33,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_DIPLOMATICO_TEXT.value,
                        "start_x": 42,
                        "start_y": 60,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'AB-1234'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 142, 'oy': 90, 'w': 20, 'h': 10, 'r': False},
                                                 {'ox': 174, 'oy': 60, 'w': 38, 'h': 70, 'r': False},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['CC', 'CD', 'OI', 'AT']},
                             {'type': 0, 'r': 0, 'text_obj': '-'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 9999, 'zfil': 4},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": EcuadorPlateColor.VEHICULOS_DIPLOMATICO_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Ecuador/Ant_Logo.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 30,
                        "start_y": 6,
                        "width": 20,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ECUADOR",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_DIPLOMATICO_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 129,
                        "start_y": 7,
                        "width": 146,
                        "height": 27,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ANT",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_DIPLOMATICO_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 32,
                        "start_y": 28,
                        "width": 16,
                        "height": 5,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": EcuadorPlateType.VEHICULO_PRIVADO.value,
                "width": 404,
                "height": 154,
                "color_bg": EcuadorPlateColor.VEHICULO_PRIVADO_BG.value,
                "color_text": EcuadorPlateColor.VEHICULO_PRIVADO_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULO_PRIVADO_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 400,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 400,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULO_PRIVADO_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 397,
                        "height": 33,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULO_PRIVADO_TEXT.value,
                        "start_x": 17,
                        "start_y": 60,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'ABC-1234'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 167, 'oy': 90, 'w': 20, 'h': 10, 'r': False},
                                                 {'ox': 199, 'oy': 60, 'w': 38, 'h': 70, 'r': False},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'U', 'C', 'X', 'H', 'O', 'E',
                                                             'W', 'G', 'I', 'L', 'R', 'M', 'V', 'N',
                                                             'S', 'P', 'Q', 'K', 'T', 'Z', 'Y', 'J']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['B', 'C', 'D',  'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L',  'N', 'O', 'P',
                                                             'Q', 'R', 'T',  'V',  'Y']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 0, 'text_obj': '-'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 9999, 'zfil': 4},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": EcuadorPlateColor.VEHICULO_PRIVADO_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Ecuador/Ant_Logo.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 30,
                        "start_y": 6,
                        "width": 20,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ECUADOR",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULO_PRIVADO_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 129,
                        "start_y": 7,
                        "width": 146,
                        "height": 27,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ANT",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULO_PRIVADO_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 32,
                        "start_y": 28,
                        "width": 16,
                        "height": 5,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": EcuadorPlateType.VEHICULO_PRIVADO_DUPLICATA.value,
                "width": 404,
                "height": 154,
                "color_bg": EcuadorPlateColor.VEHICULO_PRIVADO_DUPLICATA_BG.value,
                "color_text": EcuadorPlateColor.VEHICULO_PRIVADO_DUPLICATA_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULO_PRIVADO_DUPLICATA_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 400,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 400,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULO_PRIVADO_DUPLICATA_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 397,
                        "height": 33,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULO_PRIVADO_DUPLICATA_TEXT.value,
                        "start_x": 17,
                        "start_y": 60,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'ABC-1234'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 167, 'oy': 90, 'w': 20, 'h': 10, 'r': False},
                                                 {'ox': 199, 'oy': 60, 'w': 38, 'h': 70, 'r': False},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'U', 'C', 'X', 'H', 'O', 'E',
                                                             'W', 'G', 'I', 'L', 'R', 'M', 'V', 'N',
                                                             'S', 'P', 'Q', 'K', 'T', 'Z', 'Y', 'J']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['B', 'C', 'D', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'N', 'O', 'P',
                                                             'Q', 'R', 'T', 'V', 'Y']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 0, 'text_obj': '-'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 9999, 'zfil': 4},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": EcuadorPlateColor.VEHICULO_PRIVADO_DUPLICATA_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Ecuador/Ant_Logo.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 30,
                        "start_y": 6,
                        "width": 20,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ECUADOR",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULO_PRIVADO_DUPLICATA_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 129,
                        "start_y": 7,
                        "width": 146,
                        "height": 27,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ANT",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULO_PRIVADO_DUPLICATA_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 32,
                        "start_y": 28,
                        "width": 16,
                        "height": 5,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"D",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULO_PRIVADO_DUPLICATA_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 360,
                        "start_y": 14,
                        "width": 16,
                        "height": 22,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": EcuadorPlateType.VEHICULOS_OFICIAL.value,
                "width": 404,
                "height": 154,
                "color_bg": EcuadorPlateColor.VEHICULOS_OFICIAL_BG.value,
                "color_text": EcuadorPlateColor.VEHICULOS_OFICIAL_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_OFICIAL_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 400,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 400,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_OFICIAL_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 397,
                        "height": 33,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_OFICIAL_TEXT.value,
                        "start_x": 17,
                        "start_y": 60,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'AXC-1234'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 167, 'oy': 90, 'w': 20, 'h': 10, 'r': False},
                                                 {'ox': 199, 'oy': 60, 'w': 38, 'h': 70, 'r': False},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'U', 'C', 'X', 'H', 'O', 'E',
                                                             'W', 'G', 'I', 'L', 'R', 'M', 'V', 'N',
                                                             'S', 'P', 'Q', 'K', 'T', 'Z', 'Y', 'J']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['X']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 0, 'text_obj': '-'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 9999, 'zfil': 4},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": EcuadorPlateColor.VEHICULOS_OFICIAL_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Ecuador/Ant_Logo.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 30,
                        "start_y": 6,
                        "width": 20,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ECUADOR",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_OFICIAL_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 129,
                        "start_y": 7,
                        "width": 146,
                        "height": 27,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ANT",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_OFICIAL_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 32,
                        "start_y": 28,
                        "width": 16,
                        "height": 5,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": EcuadorPlateType.VEHICULOS_GUBERNAMENTALES.value,
                "width": 404,
                "height": 154,
                "color_bg": EcuadorPlateColor.VEHICULOS_GUBERNAMENTALES_BG.value,
                "color_text": EcuadorPlateColor.VEHICULOS_GUBERNAMENTALES_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_GUBERNAMENTALES_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 400,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 400,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_GUBERNAMENTALES_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 397,
                        "height": 33,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_GUBERNAMENTALES_TEXT.value,
                        "start_x": 17,
                        "start_y": 60,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'AEC-1234'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 167, 'oy': 90, 'w': 20, 'h': 10, 'r': False},
                                                 {'ox': 199, 'oy': 60, 'w': 38, 'h': 70, 'r': False},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'U', 'C', 'X', 'H', 'O', 'E',
                                                             'W', 'G', 'I', 'L', 'R', 'M', 'V', 'N',
                                                             'S', 'P', 'Q', 'K', 'T', 'Z', 'Y', 'J']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['E']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 0, 'text_obj': '-'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 9999, 'zfil': 4},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": EcuadorPlateColor.VEHICULOS_GUBERNAMENTALES_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Ecuador/Ant_Logo.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 30,
                        "start_y": 6,
                        "width": 20,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ECUADOR",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_GUBERNAMENTALES_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 129,
                        "start_y": 7,
                        "width": 146,
                        "height": 27,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ANT",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_GUBERNAMENTALES_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 32,
                        "start_y": 28,
                        "width": 16,
                        "height": 5,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": EcuadorPlateType.VEHICULOS_REGIONES.value,
                "width": 404,
                "height": 154,
                "color_bg": EcuadorPlateColor.VEHICULOS_REGIONES_BG.value,
                "color_text": EcuadorPlateColor.VEHICULOS_REGIONES_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_REGIONES_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 400,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 400,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_REGIONES_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 397,
                        "height": 33,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_REGIONES_TEXT.value,
                        "start_x": 17,
                        "start_y": 60,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'AEC-1234'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 167, 'oy': 90, 'w': 20, 'h': 10, 'r': False},
                                                 {'ox': 199, 'oy': 60, 'w': 38, 'h': 70, 'r': False},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'U', 'C', 'X', 'H', 'O', 'E',
                                                             'W', 'G', 'I', 'L', 'R', 'M', 'V', 'N',
                                                             'S', 'P', 'Q', 'K', 'T', 'Z', 'Y', 'J']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['M', 'S']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 0, 'text_obj': '-'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 9999, 'zfil': 4},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": EcuadorPlateColor.VEHICULOS_REGIONES_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Ecuador/Ant_Logo.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 30,
                        "start_y": 6,
                        "width": 20,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ECUADOR",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_REGIONES_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 129,
                        "start_y": 7,
                        "width": 146,
                        "height": 27,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ANT",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_REGIONES_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 32,
                        "start_y": 28,
                        "width": 16,
                        "height": 5,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": EcuadorPlateType.VEHICULOS_COMERCIALES.value,
                "width": 404,
                "height": 154,
                "color_bg": EcuadorPlateColor.VEHICULOS_COMERCIALES_BG.value,
                "color_text": EcuadorPlateColor.VEHICULOS_COMERCIALES_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_COMERCIALES_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 400,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 400,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_COMERCIALES_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 397,
                        "height": 33,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_COMERCIALES_TEXT.value,
                        "start_x": 17,
                        "start_y": 60,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'AEC-1234'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 167, 'oy': 90, 'w': 20, 'h': 10, 'r': False},
                                                 {'ox': 199, 'oy': 60, 'w': 38, 'h': 70, 'r': False},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'U', 'C', 'X', 'H', 'O', 'E',
                                                             'W', 'G', 'I', 'L', 'R', 'M', 'V', 'N',
                                                             'S', 'P', 'Q', 'K', 'T', 'Z', 'Y', 'J']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'A', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 0, 'text_obj': '-'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 9999, 'zfil': 4},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": EcuadorPlateColor.VEHICULOS_COMERCIALES_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Ecuador/Ant_Logo.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 30,
                        "start_y": 6,
                        "width": 20,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ECUADOR",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_COMERCIALES_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 129,
                        "start_y": 7,
                        "width": 146,
                        "height": 27,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ANT",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_COMERCIALES_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 32,
                        "start_y": 28,
                        "width": 16,
                        "height": 5,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": EcuadorPlateType.VEHICULO_POLICIA.value,
                "width": 404,
                "height": 154,
                "color_bg": EcuadorPlateColor.VEHICULO_POLICIA_BG.value,
                "color_text": EcuadorPlateColor.VEHICULO_POLICIA_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULO_POLICIA_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 400,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 400,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULO_POLICIA_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 397,
                        "height": 33,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULO_POLICIA_TEXT.value,
                        "start_x": 17,
                        "start_y": 60,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'AEC-1234'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 167, 'oy': 90, 'w': 20, 'h': 10, 'r': False},
                                                 {'ox': 199, 'oy': 60, 'w': 38, 'h': 70, 'r': False},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'U', 'C', 'X', 'H', 'O', 'E',
                                                             'W', 'G', 'I', 'L', 'R', 'M', 'V', 'N',
                                                             'S', 'P', 'Q', 'K', 'T', 'Z', 'Y', 'J']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['W']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 0, 'text_obj': '-'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 9999, 'zfil': 4},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": EcuadorPlateColor.VEHICULO_POLICIA_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Ecuador/Ant_Logo.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 30,
                        "start_y": 6,
                        "width": 20,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ECUADOR",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULO_POLICIA_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 129,
                        "start_y": 7,
                        "width": 146,
                        "height": 27,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ANT",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULO_POLICIA_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 32,
                        "start_y": 28,
                        "width": 16,
                        "height": 5,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": EcuadorPlateType.VEHICULOS_TEMPORAL.value,
                "width": 404,
                "height": 154,
                "color_bg": EcuadorPlateColor.VEHICULOS_TEMPORAL_BG.value,
                "color_text": EcuadorPlateColor.VEHICULOS_TEMPORAL_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_TEMPORAL_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.VEHICULOS_TEMPORAL_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 400,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.VEHICULOS_TEMPORAL_SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 400,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_TEMPORAL_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 397,
                        "height": 33,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_TEMPORAL_TEXT.value,
                        "start_x": 42,
                        "start_y": 60,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'ABC-1234'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 192, 'oy': 90, 'w': 20, 'h': 10, 'r': False},
                                                 {'ox': 224, 'oy': 60, 'w': 38, 'h': 70, 'r': False},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'U', 'C', 'X', 'H', 'O', 'E',
                                                             'W', 'G', 'I', 'L', 'R', 'M', 'V', 'N',
                                                             'S', 'P', 'Q', 'K', 'T', 'Z', 'Y', 'J']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['B', 'C', 'D', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'N', 'O', 'P',
                                                             'Q', 'R', 'T', 'V', 'Y']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                                             'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 0, 'text_obj': '-'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": EcuadorPlateColor.VEHICULOS_TEMPORAL_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Ecuador/Ant_Logo.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 30,
                        "start_y": 6,
                        "width": 20,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ECUADOR",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_TEMPORAL_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 129,
                        "start_y": 7,
                        "width": 146,
                        "height": 27,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ANT",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_TEMPORAL_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 32,
                        "start_y": 28,
                        "width": 16,
                        "height": 5,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            },
            {
                "name": EcuadorPlateType.VEHICULOS_INTERNACION_TEMPORAL.value,
                "width": 404,
                "height": 154,
                "color_bg": EcuadorPlateColor.VEHICULOS_INTERNACION_TEMPORAL_BG.value,
                "color_text": EcuadorPlateColor.VEHICULOS_INTERNACION_TEMPORAL_TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_INTERNACION_TEMPORAL_BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 0,
                        "start_x": 5,
                        "start_y": 85,
                        "end_x": 400,
                        "end_y": 85,
                    },
                    {
                        "type": "sine_wave",
                        "fill_color": EcuadorPlateColor.SINE_WAVE.value,
                        "wave_width": 2,
                        "wave_period": 54,
                        "wave_amplitude": 7,
                        "wave_phase": 12,
                        "start_x": 5,
                        "start_y": 86,
                        "end_x": 400,
                        "end_y": 86,
                    },
                    {
                        "type": "rectangle",
                        "fill_color": EcuadorPlateColor.VEHICULOS_INTERNACION_TEMPORAL_RECT.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 4,
                        "start_y": 4,
                        "width": 397,
                        "height": 33,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_INTERNACION_TEMPORAL_TEXT.value,
                        "start_x": 42,
                        "start_y": 60,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'AB-1234'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 142, 'oy': 90, 'w': 20, 'h': 10, 'r': False},
                                                 {'ox': 174, 'oy': 60, 'w': 38, 'h': 70, 'r': False},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70},
                                                 {'ox': 12, 'oy': 0, 'w': 38, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 1, 'rnd_obj': ['IT']},
                             {'type': 0, 'r': 0, 'text_obj': '-'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 9999, 'zfil': 4},
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": EcuadorPlateColor.VEHICULOS_INTERNACION_TEMPORAL_TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 404,
                        "height": 154,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Ecuador/Ant_Logo.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 30,
                        "start_y": 6,
                        "width": 20,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ECUADOR",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_INTERNACION_TEMPORAL_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 129,
                        "start_y": 7,
                        "width": 146,
                        "height": 27,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"ANT",
                        "color_bg": EcuadorPlateColor.TRANSPARENT_BG.value,
                        "color_text": EcuadorPlateColor.VEHICULOS_INTERNACION_TEMPORAL_TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 32,
                        "start_y": 28,
                        "width": 16,
                        "height": 5,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                ]
            }
        ]
    }
