from enum import Enum


class GuatemalaPlateType(Enum):
    VEHICULO_DE_ALQUILER = 'Vehículo de alquiler'
    VEHICULO_COMERCIAL = 'Vehículo Comercial'
    CUERPO_CONSULAR = 'Cuerpo Consular'
    CUERPO_DIPLOMATICO = 'Cuerpo Diplomático'
    MISION_INTERNACIONAL = 'Misión Internacional'
    VEHICULO_OFICIAL = 'Vehículo Oficial'
    VEHICULO_PRIVADO = 'Vehículo Privado'
    TRANSPORTE_EXTRAURBANO = 'Transporte Extraurbano de Personas o Carga'
    BUS_URBANO = 'Bus urbano'


class GuatemalaPlateColor(Enum):
    TRANSPARENT_BG = (255, 255, 255, 0)
    UPPER_RECTANGLE = (16, 59, 188)
    BG = (255, 255, 255)
    TEXT = (0, 0, 0)


def plate_guatemala():
    return {
        "country": "Guatemala",
        "rfy": "2021",  # registration format year
        "font": "EuroPlate.ttf",
        "plates": [
            {
                "name": GuatemalaPlateType.VEHICULO_DE_ALQUILER.value,
                "width": 300,
                "height": 152,
                "color_bg": GuatemalaPlateColor.BG.value,
                "color_text": GuatemalaPlateColor.TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 300,
                        "height": 152,
                        "coord": 0
                    },
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.UPPER_RECTANGLE.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 5,
                        "start_y": 5,
                        "width": 290,
                        "height": 34,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "start_x": 20,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'A123ABC'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 10, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 0, 'text_obj': 'A'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']}
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": GuatemalaPlateColor.TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 2,
                        "start_y": 2,
                        "width": 296,
                        "height": 146,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/guatemala_holografico.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 252,
                        "start_y": 14,
                        "width": 30,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/Coat_of_arms_of_Guatemala.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 12,
                        "start_y": 10,
                        "width": 25,
                        "height": 25,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"GUATEMALA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 95,
                        "start_y": 14,
                        "width": 110,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"CENTRO AMÉRICA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 72,
                        "start_y": 122,
                        "width": 159,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 4,
                        "letters": None,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 255,
                        "start_y": 29,
                        "width": 24,
                        "height": 4,
                        "offset_x": 0,
                        "coord": 0
                    }
                ]
            },
            {
                "name": GuatemalaPlateType.VEHICULO_COMERCIAL.value,
                "width": 300,
                "height": 152,
                "color_bg": GuatemalaPlateColor.BG.value,
                "color_text": GuatemalaPlateColor.TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 300,
                        "height": 152,
                        "coord": 0
                    },
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.UPPER_RECTANGLE.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 5,
                        "start_y": 5,
                        "width": 290,
                        "height": 34,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "start_x": 20,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'A123ABC'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 10, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 0, 'text_obj': 'C'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']}
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": GuatemalaPlateColor.TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 2,
                        "start_y": 2,
                        "width": 296,
                        "height": 146,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/guatemala_holografico.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 252,
                        "start_y": 14,
                        "width": 30,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/Coat_of_arms_of_Guatemala.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 12,
                        "start_y": 10,
                        "width": 25,
                        "height": 25,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"GUATEMALA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 95,
                        "start_y": 14,
                        "width": 110,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"CENTRO AMÉRICA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 72,
                        "start_y": 122,
                        "width": 159,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 4,
                        "letters": None,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 255,
                        "start_y": 29,
                        "width": 24,
                        "height": 4,
                        "offset_x": 0,
                        "coord": 0
                    }
                ]
            },
            {
                "name": GuatemalaPlateType.CUERPO_CONSULAR.value,
                "width": 300,
                "height": 152,
                "color_bg": GuatemalaPlateColor.BG.value,
                "color_text": GuatemalaPlateColor.TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 300,
                        "height": 152,
                        "coord": 0
                    },
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.UPPER_RECTANGLE.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 5,
                        "start_y": 5,
                        "width": 290,
                        "height": 34,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "start_x": 20,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'A123ABC'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 10, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 0, 'text_obj': 'CC'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 99, 'zfil': 2},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']}
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": GuatemalaPlateColor.TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 2,
                        "start_y": 2,
                        "width": 296,
                        "height": 146,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/guatemala_holografico.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 252,
                        "start_y": 14,
                        "width": 30,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/Coat_of_arms_of_Guatemala.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 12,
                        "start_y": 10,
                        "width": 25,
                        "height": 25,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"GUATEMALA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 95,
                        "start_y": 14,
                        "width": 110,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"CENTRO AMÉRICA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 72,
                        "start_y": 122,
                        "width": 159,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 4,
                        "letters": None,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 255,
                        "start_y": 29,
                        "width": 24,
                        "height": 4,
                        "offset_x": 0,
                        "coord": 0
                    }
                ]
            },
            {
                "name": GuatemalaPlateType.CUERPO_DIPLOMATICO.value,
                "width": 300,
                "height": 152,
                "color_bg": GuatemalaPlateColor.BG.value,
                "color_text": GuatemalaPlateColor.TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 300,
                        "height": 152,
                        "coord": 0
                    },
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.UPPER_RECTANGLE.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 5,
                        "start_y": 5,
                        "width": 290,
                        "height": 34,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "start_x": 20,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'A123ABC'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 10, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 0, 'text_obj': 'CD'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 99, 'zfil': 2},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']}
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": GuatemalaPlateColor.TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 2,
                        "start_y": 2,
                        "width": 296,
                        "height": 146,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/guatemala_holografico.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 252,
                        "start_y": 14,
                        "width": 30,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/Coat_of_arms_of_Guatemala.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 12,
                        "start_y": 10,
                        "width": 25,
                        "height": 25,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"GUATEMALA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 95,
                        "start_y": 14,
                        "width": 110,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"CENTRO AMÉRICA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 72,
                        "start_y": 122,
                        "width": 159,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 4,
                        "letters": None,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 255,
                        "start_y": 29,
                        "width": 24,
                        "height": 4,
                        "offset_x": 0,
                        "coord": 0
                    }
                ]
            },
            {
                "name": GuatemalaPlateType.MISION_INTERNACIONAL.value,
                "width": 300,
                "height": 152,
                "color_bg": GuatemalaPlateColor.BG.value,
                "color_text": GuatemalaPlateColor.TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 300,
                        "height": 152,
                        "coord": 0
                    },
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.UPPER_RECTANGLE.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 5,
                        "start_y": 5,
                        "width": 290,
                        "height": 34,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "start_x": 20,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'A123ABC'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 10, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 0, 'text_obj': 'MI'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 99, 'zfil': 2},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']}
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": GuatemalaPlateColor.TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 2,
                        "start_y": 2,
                        "width": 296,
                        "height": 146,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/guatemala_holografico.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 252,
                        "start_y": 14,
                        "width": 30,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/Coat_of_arms_of_Guatemala.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 12,
                        "start_y": 10,
                        "width": 25,
                        "height": 25,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"GUATEMALA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 95,
                        "start_y": 14,
                        "width": 110,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"CENTRO AMÉRICA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 72,
                        "start_y": 122,
                        "width": 159,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 4,
                        "letters": None,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 255,
                        "start_y": 29,
                        "width": 24,
                        "height": 4,
                        "offset_x": 0,
                        "coord": 0
                    }
                ]
            },
            {
                "name": GuatemalaPlateType.VEHICULO_OFICIAL.value,
                "width": 300,
                "height": 152,
                "color_bg": GuatemalaPlateColor.BG.value,
                "color_text": GuatemalaPlateColor.TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 300,
                        "height": 152,
                        "coord": 0
                    },
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.UPPER_RECTANGLE.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 5,
                        "start_y": 5,
                        "width": 290,
                        "height": 34,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "start_x": 20,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'A123ABC'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 10, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 0, 'text_obj': 'O'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']}
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": GuatemalaPlateColor.TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 2,
                        "start_y": 2,
                        "width": 296,
                        "height": 146,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/guatemala_holografico.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 252,
                        "start_y": 14,
                        "width": 30,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/Coat_of_arms_of_Guatemala.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 12,
                        "start_y": 10,
                        "width": 25,
                        "height": 25,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"GUATEMALA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 95,
                        "start_y": 14,
                        "width": 110,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"CENTRO AMÉRICA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 72,
                        "start_y": 122,
                        "width": 159,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 4,
                        "letters": None,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 255,
                        "start_y": 29,
                        "width": 24,
                        "height": 4,
                        "offset_x": 0,
                        "coord": 0
                    }
                ]
            },
            {
                "name": GuatemalaPlateType.VEHICULO_PRIVADO.value,
                "width": 300,
                "height": 152,
                "color_bg": GuatemalaPlateColor.BG.value,
                "color_text": GuatemalaPlateColor.TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 300,
                        "height": 152,
                        "coord": 0
                    },
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.UPPER_RECTANGLE.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 5,
                        "start_y": 5,
                        "width": 290,
                        "height": 34,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "start_x": 20,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'A123ABC'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 10, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 0, 'text_obj': 'P'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']}
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": GuatemalaPlateColor.TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 2,
                        "start_y": 2,
                        "width": 296,
                        "height": 146,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/guatemala_holografico.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 252,
                        "start_y": 14,
                        "width": 30,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/Coat_of_arms_of_Guatemala.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 12,
                        "start_y": 10,
                        "width": 25,
                        "height": 25,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"GUATEMALA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 95,
                        "start_y": 14,
                        "width": 110,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"CENTRO AMÉRICA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 72,
                        "start_y": 122,
                        "width": 159,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 4,
                        "letters": None,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 255,
                        "start_y": 29,
                        "width": 24,
                        "height": 4,
                        "offset_x": 0,
                        "coord": 0
                    }
                ]
            },
            {
                "name": GuatemalaPlateType.TRANSPORTE_EXTRAURBANO.value,
                "width": 300,
                "height": 152,
                "color_bg": GuatemalaPlateColor.BG.value,
                "color_text": GuatemalaPlateColor.TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 300,
                        "height": 152,
                        "coord": 0
                    },
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.UPPER_RECTANGLE.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 5,
                        "start_y": 5,
                        "width": 290,
                        "height": 34,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "start_x": 20,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'A123ABC'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 10, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 0, 'text_obj': 'TE'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 99, 'zfil': 2},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']}
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": GuatemalaPlateColor.TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 2,
                        "start_y": 2,
                        "width": 296,
                        "height": 146,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/guatemala_holografico.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 252,
                        "start_y": 14,
                        "width": 30,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/Coat_of_arms_of_Guatemala.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 12,
                        "start_y": 10,
                        "width": 25,
                        "height": 25,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"GUATEMALA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 95,
                        "start_y": 14,
                        "width": 110,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"CENTRO AMÉRICA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 72,
                        "start_y": 122,
                        "width": 159,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 4,
                        "letters": None,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 255,
                        "start_y": 29,
                        "width": 24,
                        "height": 4,
                        "offset_x": 0,
                        "coord": 0
                    }
                ]
            },
            {
                "name": GuatemalaPlateType.BUS_URBANO.value,
                "width": 300,
                "height": 152,
                "color_bg": GuatemalaPlateColor.BG.value,
                "color_text": GuatemalaPlateColor.TEXT.value,
                "object": [
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.BG.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 0,
                        "start_y": 0,
                        "width": 300,
                        "height": 152,
                        "coord": 0
                    },
                    {
                        "type": "rectangle",
                        "fill_color": GuatemalaPlateColor.UPPER_RECTANGLE.value,
                        "border_color": None,
                        "border_width": 1,
                        "quantity": 1,
                        "start_x": 5,
                        "start_y": 5,
                        "width": 290,
                        "height": 34,
                        "coord": 0
                    },
                    {
                        "type": "format",
                        "random": 1,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "start_x": 20,
                        "start_y": 42,
                        "width": 266,
                        "height": 80,
                        "coord": 0,
                        "obj": [
                            [{'type': 2, 'name': 'A123ABC'},
                             {'type': 3, 'obj': [{'ox': 0, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 10, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 31, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70},
                                                 {'ox': 5, 'oy': 0, 'w': 32, 'h': 70}]},
                             {'type': 5, 'sl': {}},
                             {'type': 0, 'r': 0, 'text_obj': 'U'},
                             {'type': 1, 'r': 1, 'min': 0, 'max': 999, 'zfil': 3},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']},
                             {'type': 0, 'r': 1, 'rnd_obj': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                                             'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                                                             'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']}
                             ]
                        ]
                    },
                    {
                        "type": "rectangle_rounded",
                        "fill_color": None,
                        "border_color": GuatemalaPlateColor.TEXT.value,
                        "border_width": 4,
                        "border_radius": 10,
                        "quantity": 1,
                        "start_x": 2,
                        "start_y": 2,
                        "width": 296,
                        "height": 146,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/guatemala_holografico.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 252,
                        "start_y": 14,
                        "width": 30,
                        "height": 20,
                        "coord": 0
                    },
                    {
                        "type": "image",
                        "image": "img/Guatemala/Coat_of_arms_of_Guatemala.png",
                        "random": 0,
                        "letters": None,
                        "quantity": 1,
                        "start_x": 12,
                        "start_y": 10,
                        "width": 25,
                        "height": 25,
                        "coord": 0
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"GUATEMALA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.BG.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 95,
                        "start_y": 14,
                        "width": 110,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 0,
                        "letters": u"CENTRO AMÉRICA",
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 72,
                        "start_y": 122,
                        "width": 159,
                        "height": 17,
                        "offset_x": 10,
                        "coord": 0,
                        "font": "ARIALN.TTF"
                    },
                    {
                        "type": "text",
                        "random": 4,
                        "letters": None,
                        "color_bg": GuatemalaPlateColor.TRANSPARENT_BG.value,
                        "color_text": GuatemalaPlateColor.TEXT.value,
                        "by_letter": 0,
                        "quantity": 0,
                        "start_x": 255,
                        "start_y": 29,
                        "width": 24,
                        "height": 4,
                        "offset_x": 0,
                        "coord": 0
                    }
                ]
            }
        ]
    }
